# Generated by Django 2.0.4 on 2018-10-10 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='l', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Id',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='vid', max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('length', models.FloatField(default=0.0)),
                ('played', models.IntegerField(default=0)),
                ('liked', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to='upload')),
                ('time', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Id')),
            ],
        ),
        migrations.AddField(
            model_name='behavior',
            name='aim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Item'),
        ),
        migrations.AddField(
            model_name='behavior',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Id'),
        ),
    ]
