# Generated by Django 2.0.4 on 2018-10-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='avatar',
            field=models.FileField(default=None, upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='uploaded'),
        ),
    ]
