# Generated by Django 2.0.4 on 2018-10-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181011_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
