# Generated by Django 2.0.4 on 2018-10-15 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_item_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='length',
        ),
    ]
