# Generated by Django 2.0.4 on 2018-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_item_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.CharField(default='fun', max_length=20),
        ),
    ]
